color:
  brandColors:
    - '#090806'
    - '#404E57'
    - '#FAFFC5'
    - '#A48F7A'
    - '#FCE734'
  brandStrength: 1
  lightness: 0.668617
  rhythmicContrast: 0.646115
  saturation: 0.733953
layout_spectrum: 1
name: Just a Guy in Vegas
typography_spectrum: 0.388514
