color:
  brandColors:
    - '#0C0A0B'
    - '#F5FFFF'
    - '#A8115E'
    - '#490C47'
    - '#6E5D3F'
  brandStrength: 1
  lightness: 0.668617
  rhythmicContrast: 0.646115
  saturation: 0.733953
layout_spectrum: 1
name: Just a Guy in Vegas
typography_spectrum: 0.388514
