color:
  brandColors:
    - '#F2F1F6'
    - '#DCDCE4'
    - '#000100'
    - '#E0B099'
    - '#37354A'
  brandStrength: 1
  lightness: 0.668617
  rhythmicContrast: 0.646115
  saturation: 0.733953
layout_spectrum: 0.786318
name: Just a Guy in Vegas
typography_spectrum: 0.388514
