color:
  brandColors:
    - '#8A8D96'
    - '#666B71'
    - '#B1AEB5'
    - '#9A9DA6'
    - '#C2C5CC'
  brandStrength: 0.338682
  lightness: 0.668617
  rhythmicContrast: 0.646115
  saturation: 0.733953
layout_spectrum: 0.988176
name: Just a Guy in Vegas
typography_spectrum: 0.30616698297671974
